apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: weave-scope-app
    app: weave-scope
    weave-cloud-component: scope
    weave-scope-component: app
  name: weave-scope-app
spec:
  ports:
    - name: app
      port: 80
      targetPort: 4040
      protocol: TCP
  selector:
    name: weave-scope-app
    app: weave-scope
    weave-cloud-component: scope
    weave-scope-component: app
