apiVersion: v1
kind: Service
metadata:
  name: weave-scope
spec:
  type: NodePort
  ports:
  - port: 80 
    targetPort: 80
    nodePort: 30042
    protocol: TCP
    name: weave-scope

  selector:
    name: weave-scope
