apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-4b19761",
        "original-request": {
          "url": "/k8s/v1.5/scope.yaml?/launch/k8s/weavescope.yaml",
          "date": "Fri Apr 07 2017 02:00:39 GMT+0000 (UTC)"
        },
        "email-address": "support@weave.works"
      }
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"cloud.weave.works/launcher-info":"{\n  \"server-version\": \"master-4b19761\",\n  \"original-request\": {\n    \"url\": \"/k8s/v1.5/scope.yaml?/launch/k8s/weavescope.yaml\",\n    \"date\": \"Fri Apr 07 2017 02:00:39 GMT+0000 (UTC)\"\n  },\n  \"email-address\": \"support@weave.works\"\n}"},"labels":{"name":"weave-scope"},"name":"weave-scope","namespace":"default"}}
  creationTimestamp: 2017-04-07T02:00:39Z
  labels:
    name: weave-scope
  name: weave-scope
  namespace: default
  resourceVersion: "8834"
  selfLink: /api/v1/namespaces/default/serviceaccounts/weave-scope
  uid: fff7cf4a-1b35-11e7-8ace-80fa5b3b6001
secrets:
- name: weave-scope-token-3xk0q
