apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-4b19761",
        "original-request": {
          "url": "/k8s/v1.5/scope.yaml?/launch/k8s/weavescope.yaml",
          "date": "Fri Apr 07 2017 02:00:39 GMT+0000 (UTC)"
        },
        "email-address": "support@weave.works"
      }
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.weave.works/launcher-info":"{\n  \"server-version\": \"master-4b19761\",\n  \"original-request\": {\n    \"url\": \"/k8s/v1.5/scope.yaml?/launch/k8s/weavescope.yaml\",\n    \"date\": \"Fri Apr 07 2017 02:00:39 GMT+0000 (UTC)\"\n  },\n  \"email-address\": \"support@weave.works\"\n}"},"labels":{"app":"weave-scope","name":"weave-scope-app","weave-cloud-component":"scope","weave-scope-component":"app"},"name":"weave-scope-app","namespace":"default"},"spec":{"ports":[{"name":"app","port":80,"protocol":"TCP","targetPort":4040}],"selector":{"app":"weave-scope","name":"weave-scope-app","weave-cloud-component":"scope","weave-scope-component":"app"}}}
  labels:
    app: weave-scope
    name: weave-scope-app
    weave-cloud-component: scope
    weave-scope-component: app
  name: weave-scope-app
  namespace: default
  resourceVersion: "8837"
  selfLink: /api/v1/namespaces/default/services/weave-scope-app
  uid: fffa1540-1b35-11e7-8ace-80fa5b3b6001
spec:
  clusterIP: 10.101.62.214
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 4040
  selector:
    app: weave-scope
    name: weave-scope-app
    weave-cloud-component: scope
    weave-scope-component: app
  sessionAffinity: None
  type: ClusterIP
