apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-4b19761",
        "original-request": {
          "url": "/k8s/v1.5/scope.yaml?/launch/k8s/weavescope.yaml",
          "date": "Fri Apr 07 2017 02:00:39 GMT+0000 (UTC)"
        },
        "email-address": "support@weave.works"
      }
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"cloud.weave.works/launcher-info":"{\n  \"server-version\": \"master-4b19761\",\n  \"original-request\": {\n    \"url\": \"/k8s/v1.5/scope.yaml?/launch/k8s/weavescope.yaml\",\n    \"date\": \"Fri Apr 07 2017 02:00:39 GMT+0000 (UTC)\"\n  },\n  \"email-address\": \"support@weave.works\"\n}"},"labels":{"app":"weave-scope","name":"weave-scope-app","weave-cloud-component":"scope","weave-scope-component":"app"},"name":"weave-scope-app","namespace":"default"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"app":"weave-scope","name":"weave-scope-app","weave-cloud-component":"scope","weave-scope-component":"app"}},"spec":{"containers":[{"args":["--no-probe"],"image":"weaveworks/scope:1.3.0","imagePullPolicy":"IfNotPresent","name":"app","ports":[{"containerPort":4040,"protocol":"TCP"}]}]}}}}
  labels:
    app: weave-scope
    name: weave-scope-app
    weave-cloud-component: scope
    weave-scope-component: app
  name: weave-scope-app
  namespace: default
  resourceVersion: "8872"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/weave-scope-app
  uid: fff87566-1b35-11e7-8ace-80fa5b3b6001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weave-scope
      name: weave-scope-app
      weave-cloud-component: scope
      weave-scope-component: app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: weave-scope
        name: weave-scope-app
        weave-cloud-component: scope
        weave-scope-component: app
    spec:
      containers:
      - args:
        - --no-probe
        image: weaveworks/scope:1.3.0
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 4040
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
