apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-4b19761",
        "original-request": {
          "url": "/k8s/v1.5/scope.yaml?/launch/k8s/weavescope.yaml",
          "date": "Fri Apr 07 2017 02:00:39 GMT+0000 (UTC)"
        },
        "email-address": "support@weave.works"
      }
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{"cloud.weave.works/launcher-info":"{\n  \"server-version\": \"master-4b19761\",\n  \"original-request\": {\n    \"url\": \"/k8s/v1.5/scope.yaml?/launch/k8s/weavescope.yaml\",\n    \"date\": \"Fri Apr 07 2017 02:00:39 GMT+0000 (UTC)\"\n  },\n  \"email-address\": \"support@weave.works\"\n}"},"labels":{"app":"weave-scope","name":"weave-scope-agent","weave-cloud-component":"scope","weave-scope-component":"agent"},"name":"weave-scope-agent","namespace":"default"},"spec":{"template":{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/tolerations":"[{\"key\":\"dedicated\",\"operator\":\"Equal\",\"value\":\"master\",\"effect\":\"NoSchedule\"}]"},"labels":{"app":"weave-scope","name":"weave-scope-agent","weave-cloud-component":"scope","weave-scope-component":"agent"}},"spec":{"containers":[{"args":["--no-app","--probe.docker.bridge=docker0","--probe.docker=true","--probe.kubernetes=true","$(WEAVE_SCOPE_APP_SERVICE_HOST):$(WEAVE_SCOPE_APP_SERVICE_PORT)"],"image":"weaveworks/scope:1.3.0","imagePullPolicy":"IfNotPresent","name":"agent","securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/var/run/docker.sock","name":"docker-socket"},{"mountPath":"/var/run/scope/plugins","name":"scope-plugins"}]}],"hostNetwork":true,"hostPID":true,"serviceAccountName":"weave-scope","volumes":[{"hostPath":{"path":"/var/run/docker.sock"},"name":"docker-socket"},{"hostPath":{"path":"/var/run/scope/plugins"},"name":"scope-plugins"}]}}}}
  creationTimestamp: 2017-04-07T02:00:39Z
  generation: 1
  labels:
    app: weave-scope
    name: weave-scope-agent
    weave-cloud-component: scope
    weave-scope-component: agent
  name: weave-scope-agent
  namespace: default
  resourceVersion: "8868"
  selfLink: /apis/extensions/v1beta1/namespaces/default/daemonsets/weave-scope-agent
  uid: fffb355d-1b35-11e7-8ace-80fa5b3b6001
spec:
  selector:
    matchLabels:
      app: weave-scope
      name: weave-scope-agent
      weave-cloud-component: scope
      weave-scope-component: agent
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"dedicated","operator":"Equal","value":"master","effect":"NoSchedule"}]'
      creationTimestamp: null
      labels:
        app: weave-scope
        name: weave-scope-agent
        weave-cloud-component: scope
        weave-scope-component: agent
    spec:
      containers:
      - args:
        - --no-app
        - --probe.docker.bridge=docker0
        - --probe.docker=true
        - --probe.kubernetes=true
        - $(WEAVE_SCOPE_APP_SERVICE_HOST):$(WEAVE_SCOPE_APP_SERVICE_PORT)
        image: weaveworks/scope:1.3.0
        imagePullPolicy: IfNotPresent
        name: agent
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
        - mountPath: /var/run/scope/plugins
          name: scope-plugins
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: weave-scope
      serviceAccountName: weave-scope
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/run/docker.sock
        name: docker-socket
      - hostPath:
          path: /var/run/scope/plugins
        name: scope-plugins
  templateGeneration: 1
  updateStrategy:
    type: OnDelete
